{
    'name': 'Clinic consult view',
    'version': '8.0.1.1.0',
    'category': 'Clinic',
    'depends': [
        'medical',
        'medical_prescription',
        'sl_patient_medical_history',
        'sl_medical_consult',
        'sl_patient_triage',
        'sl_medical_disease',
        'sl_medical_security',
        'sl_prescription_report',
        'sl_medical_consult_payment',
    ],
    'author': 'Luis Paredes para Softlab Perú SAC',
    'website': 'http://www.softlabperu.com',
    'license': 'AGPL-3',
    'data': [
        'views/medical_consult.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
