{
    'name': 'Step2 clinic install',
    'version': '8.0.1.1.0',
    'category': 'Clinic',
    'depends': [
        'sl_pacient_general_information',
        'sl_patient_medical_biological_functions',
        'sl_medical_security',
        'sl_clinic_procedure',
        'sl_medical_medicament',
        'sl_patient_medical_history',
        'sl_medical_surgeries',
        'sl_medical_prescription',
        'sl_ambulatory_care',
        'sl_patient_triage',
        'sl_medical_testlab',
        'sl_medical_consult',
        'sl_medical_inpatient_admission',
        'sl_medical_inpatient_admission_prescription',
        'sl_medical_disease',
    ],
    'author': 'Luis Paredes para Softlab Perú SAC',
    'website': 'http://www.softlabperu.com',
    'license': 'AGPL-3',
    'data': [
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
