{
    'name': 'Odoo clinic patient view',
    'version': '8.0.1.1.0',
    'category': 'Clinic',
    'depends': [
        'medical',
        'partner_firstname',
        'partner_second_lastname',
        'medical_prescription',
        'medical_his',
        'medical_disease',
        'sl_patient_medical_history',
        #'sl_patient_appointment',
        'sl_pacient_general_information',
        #'sl_patient_type_document',
        'sl_patient_medical_biological_functions',
        'sl_patient_triage',
        'sl_medical_consult',
        'sl_medical_consult_view',
        'sl_medical_prescription',
        'sl_medical_surgeries',
        'sl_clinic_procedure',
        'sl_ambulatory_care',
        'medical_disease',
        'sl_medical_inpatient_admission',
        'sl_medical_inpatient_admission_view',
        'product',
        'sl_medical_medicament',
        'sl_medical_security',
        'sl_medical_pediatric',
        'sl_medical_procedure_sale',
        'sl_medical_test_sale',
        'sl_medical_inpatient_admission_prescription'
    ],
    'author': 'Luis Paredes para Softlab Perú SAC',
    'website': 'http://www.softlabperu.com',
    'license': 'AGPL-3',
    'data': [
#        'views/appointment_view.xml',
        'views/triage_view.xml',
        "views/biological_functions_view.xml",
        #"views/typedocument.xml",
        'views/prescription_view.xml',
        'views/test_type_view.xml',
        'views/testlab_view.xml',
        'views/testimage_view.xml',
        'views/clinic_prescription_line_view.xml',
        'views/clinic_prescription_order_view.xml',
        'views/physician_view.xml',
        'views/surgeries_view.xml',
        'views/patient_view.xml',
        'views/ambulatory_care_view.xml',
        'views/patient_disease_view.xml',
        'views/product_product_view.xml',
        'views/procedure_view.xml',
        'views/medical_medicament_view.xml',
        'views/medical_pathology_view.xml',
      #   'views/pediatric_newborn.xml',
      #   'views/vaccine.xml',
        'views/patient_menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
