{
    'name': 'Step1 clinic install',
    'version': '8.0.1.1.0',
    'category': 'Clinic',
    'depends': [
        'medical',
        'medical_disease',
        'medical_his',
        'medical_medicament',
        'medical_medication',
        'medical_patient_ethnicity',
        'medical_prescription',
        'sl_medical_translation',
        'sl_medical_disease_translation',
        'sl_medical_his_translation',
        'sl_medical_medicament_translation',
        'sl_medical_medication_translation',
        'sl_medical_prescription_translation',
    ],
    'author': 'Luis Paredes para Softlab Perú SAC',
    'website': 'http://www.softlabperu.com',
    'license': 'AGPL-3',
    'data': [
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
